FROM centos:7
MAINTAINER Jeff Sheng

RUN  cd /usr/local/src && yum install -y wget gcc gcc-c++ vim make\
        && wget https://nodejs.org/dist/v4.4.7/node-v4.4.7.tar.gz \
        && tar zxvf node-v4.4.7.tar.gz

RUN cd /usr/local/src/node-v4.4.7 && ./configure && make && make install \
        && echo $(node -v) && mkdir /usr/share/Webserver_Soap
ENV NODEW /usr/share/Webserver_Soap
COPY $PWD/Webserver_Soap_Phone_chiu $NODEW

WORKDIR $NODEW

CMD ["node","server"]


# base OS : centos:7

# make sure that
#  Elas  hostname : Elas_Mas
#  Redis hostname : R_Server