FROM elasticsearch:2.3
MAINTAINER Jeff Sheng

# Add ENV
ENV ESW /usr/share/elasticsearch
#ENV PATH $ESW/bin:$PATH
ENV ESW_BIN $ESW/bin

# Mount config
COPY $PWD/config $ESW/config

# Add plugin --- ik
RUN mkdir $ESW/plugins/ik
COPY $PWD/ik $ESW/plugins/ik

# Add plugin --- kopf 
RUN plugin install lmenezes/elasticsearch-kopf

# Change Workdir
WORKDIR $ESW_BIN

# change user
USER elasticsearch

# Setting port
EXPOSE 9200 9300

# You know , for search.
CMD ["elasticsearch"]


# Attention:
# User must to use docker run's args to set master and slave
# M : -h / -p / -u? / -Des.name.node
# N : --link / -u? / -w? / -p / -Des.discovery.zen.ping.unicast.hosts="$master_name"

# Bash file
#!/bin/bash

# Let's build an Elasticsearch Cluster
# 1st : ES Master.
#docker run -d --name es_QQ_master -h EsQQMaster -p 9200:9200 -p 9300:9300 jeffsheng/es_labber -Des.node.name='QQ_master'

# 2nd : ES Node X2.
#docker run -d --name es_QQ_nodeI --link es_QQ_master:e_mas -p 9201:9200 -p 9301:9300 jeffsheng/es_labber -Des.node.name='QQ_node-I' -Des.discovery.zen.ping.unicast.hosts='EsQQMaster'


#docker run -d --name es_QQ_nodeII --link es_QQ_master:e_mas -p 9202:9200 -p 9302:9300 jeffsheng/es_labber -Des.node.name='QQ_node-II' -Des.discovery.zen.ping.unicast.hosts="EsQQMaster"


#echo "Done!!!"



